// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20191102023219_New")]
    partial class New
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookup.Models.NativeSpecies", b =>
                {
                    b.Property<int>("NativeSpeciesId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<string>("CommonName");

                    b.Property<string>("ConservationStatus");

                    b.Property<string>("Kingdom");

                    b.Property<int>("ParkId");

                    b.Property<string>("Species");

                    b.Property<string>("SpeciesDescription");

                    b.HasKey("NativeSpeciesId");

                    b.HasIndex("ParkId");

                    b.ToTable("NativeSpecies");

                    b.HasData(
                        new
                        {
                            NativeSpeciesId = 1,
                            Class = "Mammalia",
                            CommonName = "American Black Bear",
                            ConservationStatus = "least concern",
                            Kingdom = "Animalia",
                            ParkId = 1,
                            Species = "Ursa americanus",
                            SpeciesDescription = "American black bears are omnivores, with diets varying greatly depending on season and location. They typically live in largely forested areas, but do leave forests in search of food. Sometimes they become attracted to human communities because of the immediate availability of food. The American black bear is the world's most common bear species."
                        },
                        new
                        {
                            NativeSpeciesId = 2,
                            Class = "Mammalia",
                            CommonName = "Hoary Marmot",
                            ConservationStatus = "least concern",
                            Kingdom = "Animalia",
                            ParkId = 3,
                            Species = "Marmota caligata",
                            SpeciesDescription = "The hoary marmot is a large, bulky, ground squirrel, with short, heavy limbs, and a broad head. They frequently sun themselves on rocks, spending as much as 44% of their time in the morning doing so, although they will shelter in their burrows or otherwise seek shade in especially warm weather. They forage for the rest of the day, returning to their burrows to sleep during the night and  hibernate seven to eight months a year in burrows."
                        },
                        new
                        {
                            NativeSpeciesId = 3,
                            Class = "Cataceae",
                            CommonName = "Grizzly Bear Prickly Pear Cactus",
                            ConservationStatus = "least concern",
                            Kingdom = "Plantae",
                            ParkId = 2,
                            Species = "Opuntia erinacea",
                            SpeciesDescription = "The Grizzly Bear Prickly Pear cactus forms small, low clumps with erect branches. The pads are thickly covered with long, gray, downward-pointing spines. Flower color varies from rose to yellow depending on variety and the fruit is dry and spiny."
                        },
                        new
                        {
                            NativeSpeciesId = 4,
                            Class = "Reptilia",
                            CommonName = "Desert Tortoise",
                            ConservationStatus = "vulnerable",
                            Kingdom = "Animalia",
                            ParkId = 2,
                            Species = "Gopherus agassizii",
                            SpeciesDescription = "The desert tortoise lives about 50 to 80 years; it grows slowly and generally has a low reproductive rate. Desert tortoises can live in areas with ground temperatures exceeding 140 °F (60 °C) because of their ability to dig burrows and escape the heat. At least 95% of their lives are spent in burrows, which helps them to regulate body temperature and reduce water loss. They are most active after seasonal rains and are inactive during most of the year."
                        },
                        new
                        {
                            NativeSpeciesId = 5,
                            Class = "Pinaceae",
                            CommonName = "White-barked Pine",
                            ConservationStatus = "endangered",
                            Kingdom = "Plantae",
                            ParkId = 2,
                            Species = "Pinus Albicaulis",
                            SpeciesDescription = "The whitebark pine is typically the highest-elevation pine tree found in Western US mountain ranges and often marks the tree line. Thus, it is often found as krummholz, trees growing close to the ground that have been dwarfed by exposure. In more favorable conditions, the trees may grow to 29 meters (95 ft) in height."
                        });
                });

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ParkFounded");

                    b.Property<string>("ParkLocation");

                    b.Property<string>("ParkName");

                    b.Property<string>("ParkSize");

                    b.Property<string>("ParkType");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkFounded = "1872",
                            ParkLocation = "Wyoming, Montana, and Idaho",
                            ParkName = "Yellowstone",
                            ParkSize = "3,468 sq miles",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkFounded = "1919",
                            ParkLocation = "Utah",
                            ParkName = "Zion",
                            ParkSize = "229 sq miles",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkFounded = "1910",
                            ParkLocation = "Montana",
                            ParkName = "Glacier",
                            ParkSize = "16,000 sq miles",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkFounded = "1872",
                            ParkLocation = "Washington",
                            ParkName = "Cape Disappointment",
                            ParkSize = "2,023 sq acres",
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkFounded = "1872",
                            ParkLocation = "Washington",
                            ParkName = "Wallace Falls",
                            ParkSize = "1,380 sq acres",
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            ParkFounded = "1937",
                            ParkLocation = "Oregon",
                            ParkName = "Rooster Rock",
                            ParkSize = "812 sq acres",
                            ParkType = "State"
                        });
                });

            modelBuilder.Entity("ParksLookup.Models.NativeSpecies", b =>
                {
                    b.HasOne("ParksLookup.Models.Park", "Park")
                        .WithMany("NativeSpecies")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
